version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /data:/data/db

  agisbnapifastapi:
    image: agisbnapifastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      .env
    volumes:
      - ./:/project
    command:
      - /bin/bash
      - -c
      - |
        dockerize -wait tcp://mongo:27017 -timeout 15s
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
