[tool.poetry]
name = "ag-isbnapi-fastapi"
version = "0.1.0"
description = ""
authors = ["noname2048 <sungwook.csw@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.65.1"
uvicorn = {extras = ["standard"], version = "^0.14.0"}
requests = "^2.25.1"
black = "^21.5b2"
python-dotenv = "^0.17.1"
xmltodict = "^0.12.0"
Pillow = "^8.2.0"
pymongo = "^3.11.4"

[tool.poetry.dev-dependencies]
jupyterlab = "^3.0.16"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
