"""create request_records

Revision ID: 5d55677d6f4a
Revises: 
Create Date: 2022-02-15 05:20:11.230417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d55677d6f4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('status', sa.Enum('Accepted', 'Ok', 'InternalError', 'RemoteError', name='status_type'), nullable=False),
    sa.Column('detail', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('request_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=False),
    sa.Column('proceeding_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('detail', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='request_record_pkey')
    )
    op.drop_table('request_records')
    # ### end Alembic commands ###
