"""first autogen

Revision ID: 1e40c49042e0
Revises: 
Create Date: 2021-11-03 22:40:04.143044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e40c49042e0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookrequests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("isbn", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bookrequests_id"), "bookrequests", ["id"], unique=False)
    op.create_index(
        op.f("ix_bookrequests_isbn"), "bookrequests", ["isbn"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_bookrequests_isbn"), table_name="bookrequests")
    op.drop_index(op.f("ix_bookrequests_id"), table_name="bookrequests")
    op.drop_table("bookrequests")
    # ### end Alembic commands ###
