name: learn-github-action
on:
  push:
    branches:
      - product

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          python get-poetry --yes
          poetry config virtualenvs.create false
      - name: Install dependencies
        run: |
          poetry install
      - name: Test with pytest
        run: |
          pytest
